<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `InstitucionesFinancieras`
//

// `InstitucionesFinancieras`.`instituciones`
$instituciones = array(
  array('id' => '1','tipo' => 'Bancos','codigoSBIF' => '001','codigoRegistro' => NULL,'nombre' => 'BANCO DE CHILE'),
  array('id' => '2','tipo' => 'Bancos','codigoSBIF' => '009','codigoRegistro' => NULL,'nombre' => 'BANCO INTERNACIONAL'),
  array('id' => '3','tipo' => 'Bancos','codigoSBIF' => '014','codigoRegistro' => NULL,'nombre' => 'SCOTIABANK CHILE'),
  array('id' => '4','tipo' => 'Bancos','codigoSBIF' => '016','codigoRegistro' => NULL,'nombre' => 'BANCO DE CREDITO E INVERSIONES'),
  array('id' => '5','tipo' => 'Bancos','codigoSBIF' => '027','codigoRegistro' => NULL,'nombre' => 'CORPBANCA'),
  array('id' => '6','tipo' => 'Bancos','codigoSBIF' => '028','codigoRegistro' => NULL,'nombre' => 'BANCO BICE'),
  array('id' => '7','tipo' => 'Bancos','codigoSBIF' => '031','codigoRegistro' => NULL,'nombre' => 'HSBC BANK (CHILE)'),
  array('id' => '8','tipo' => 'Bancos','codigoSBIF' => '037','codigoRegistro' => NULL,'nombre' => 'BANCO SANTANDER-CHILE'),
  array('id' => '9','tipo' => 'Bancos','codigoSBIF' => '039','codigoRegistro' => NULL,'nombre' => 'BANCO ITAÚ CHILE'),
  array('id' => '10','tipo' => 'Bancos','codigoSBIF' => '049','codigoRegistro' => NULL,'nombre' => 'BANCO SECURITY'),
  array('id' => '11','tipo' => 'Bancos','codigoSBIF' => '051','codigoRegistro' => NULL,'nombre' => 'BANCO FALABELLA'),
  array('id' => '12','tipo' => 'Bancos','codigoSBIF' => '052','codigoRegistro' => NULL,'nombre' => 'DEUTSCHE BANK (CHILE)'),
  array('id' => '13','tipo' => 'Bancos','codigoSBIF' => '053','codigoRegistro' => NULL,'nombre' => 'BANCO RIPLEY'),
  array('id' => '14','tipo' => 'Bancos','codigoSBIF' => '054','codigoRegistro' => NULL,'nombre' => 'RABOBANK CHILE (ex HNS BANCO)'),
  array('id' => '15','tipo' => 'Bancos','codigoSBIF' => '055','codigoRegistro' => NULL,'nombre' => 'BANCO CONSORCIO (ex BANCO MONEX)'),
  array('id' => '16','tipo' => 'Bancos','codigoSBIF' => '056','codigoRegistro' => NULL,'nombre' => 'BANCO PENTA'),
  array('id' => '17','tipo' => 'Bancos','codigoSBIF' => '057','codigoRegistro' => NULL,'nombre' => 'BANCO PARIS'),
  array('id' => '18','tipo' => 'Bancos','codigoSBIF' => '504','codigoRegistro' => NULL,'nombre' => 'BANCO BILBAO VIZCAYA ARGENTARIA, CHILE (BBVA)'),
  array('id' => '19','tipo' => 'Bancos','codigoSBIF' => '059','codigoRegistro' => NULL,'nombre' => 'BANCO BTG PACTUAL CHILE'),
  array('id' => '20','tipo' => 'Bancos','codigoSBIF' => '017','codigoRegistro' => NULL,'nombre' => 'BANCO DO BRASIL S.A.'),
  array('id' => '21','tipo' => 'Bancos','codigoSBIF' => '041','codigoRegistro' => NULL,'nombre' => 'JP MORGAN CHASE BANK, N. A.'),
  array('id' => '22','tipo' => 'Bancos','codigoSBIF' => '043','codigoRegistro' => NULL,'nombre' => 'BANCO DE LA NACION ARGENTINA'),
  array('id' => '23','tipo' => 'Bancos','codigoSBIF' => '045','codigoRegistro' => NULL,'nombre' => 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD'),
  array('id' => '24','tipo' => 'Bancos','codigoSBIF' => '930','codigoRegistro' => NULL,'nombre' => 'BCI - SUCURSAL MIAMI'),
  array('id' => '25','tipo' => 'Bancos','codigoSBIF' => '931','codigoRegistro' => NULL,'nombre' => 'BANCO DEL ESTADO DE CHILE - SUCURSAL NUEVA YORK'),
  array('id' => '26','tipo' => 'Bancos','codigoSBIF' => '932','codigoRegistro' => NULL,'nombre' => 'CORPBANCA - SUCURSAL NUEVA YORK'),
  array('id' => '27','tipo' => 'Bancos','codigoSBIF' => '012','codigoRegistro' => NULL,'nombre' => 'BANCO DEL ESTADO DE CHILE'),
  array('id' => '28','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '671','codigoRegistro' => NULL,'nombre' => 'COOCRETAL'),
  array('id' => '29','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '672','codigoRegistro' => NULL,'nombre' => 'COOPEUCH'),
  array('id' => '30','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '673','codigoRegistro' => NULL,'nombre' => 'ORIENCOOP'),
  array('id' => '31','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '674','codigoRegistro' => NULL,'nombre' => 'CAPUAL'),
  array('id' => '32','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '675','codigoRegistro' => NULL,'nombre' => 'DETACOOP'),
  array('id' => '33','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '676','codigoRegistro' => NULL,'nombre' => 'AHORROCOOP'),
  array('id' => '34','tipo' => 'Cooperativas de Ahorro y Crédito','codigoSBIF' => '677','codigoRegistro' => NULL,'nombre' => 'LAUTARO ROSAS'),
  array('id' => '35','tipo' => 'Operadores de Tarjetas de Débito','codigoSBIF' => '800','codigoRegistro' => NULL,'nombre' => 'Sociedad Operadora de Tarjetas S.A.'),
  array('id' => '36','tipo' => 'Asesorías Financieras','codigoSBIF' => '231','codigoRegistro' => NULL,'nombre' => 'BANCHILE ASESORIA FINANCIERA S.A. '),
  array('id' => '37','tipo' => 'Asesorías Financieras','codigoSBIF' => '235','codigoRegistro' => NULL,'nombre' => 'SCOTIA SUD AMERICANO ASESORIAS FINANCIERAS LTDA.'),
  array('id' => '38','tipo' => 'Asesorías Financieras','codigoSBIF' => '236','codigoRegistro' => NULL,'nombre' => 'BCI S.A. ASESORIA FINANCIERA'),
  array('id' => '39','tipo' => 'Asesorías Financieras','codigoSBIF' => '237','codigoRegistro' => NULL,'nombre' => 'CORPBANCA ASESORIAS FINANCIERAS S.A.'),
  array('id' => '40','tipo' => 'Asesorías Financieras','codigoSBIF' => '241','codigoRegistro' => NULL,'nombre' => 'BBVA ASESORIAS FINANCIERAS S.A.'),
  array('id' => '41','tipo' => 'Asesorías Financieras','codigoSBIF' => '245','codigoRegistro' => NULL,'nombre' => 'BANCOESTADO MICROEMPRESAS S.A.'),
  array('id' => '42','tipo' => 'Asesorías Financieras','codigoSBIF' => '248','codigoRegistro' => NULL,'nombre' => 'BANRIPLEY ASESORÍA FINANCIERA LTDA.'),
  array('id' => '43','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '261','codigoRegistro' => NULL,'nombre' => 'REDBANC S.A.'),
  array('id' => '44','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '263','codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE RECAUDACION Y PAGOS DE SERVICIOS LTDA. - Servipag'),
  array('id' => '45','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '265','codigoRegistro' => NULL,'nombre' => 'SOCIEDAD INTERBANCARIA DE DEPOSITOS DE VALORES S.A.'),
  array('id' => '46','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '267','codigoRegistro' => NULL,'nombre' => 'TRANSBANK S.A. Transbank S.A.'),
  array('id' => '47','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '268','codigoRegistro' => NULL,'nombre' => 'NEXUS S.A.'),
  array('id' => '48','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '269','codigoRegistro' => NULL,'nombre' => 'ANALISIS Y SERVICIOS S.A. - BCI NEGOCIOS'),
  array('id' => '49','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '270','codigoRegistro' => NULL,'nombre' => 'CENTRO DE COMPENSACION AUTOMATIZADO S.A.'),
  array('id' => '50','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '273','codigoRegistro' => NULL,'nombre' => 'ARTIKOS CHILE S.A.'),
  array('id' => '51','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '274','codigoRegistro' => NULL,'nombre' => 'BANCOESTADO CONTACTO 24 HORAS S.A.'),
  array('id' => '52','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '275','codigoRegistro' => NULL,'nombre' => 'PROMARKET S.A.'),
  array('id' => '53','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '278','codigoRegistro' => NULL,'nombre' => 'BANCHILE TRADE SERVICE'),
  array('id' => '54','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '277','codigoRegistro' => NULL,'nombre' => 'BANCOESTADO CENTRO DE SERVICIOS S.A.'),
  array('id' => '55','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '276','codigoRegistro' => NULL,'nombre' => 'SOCIEDAD OPERADORA DE LA CÁMARA DE COMPENSACIÓN DE PAGOS DE ALTO VALOR S.A. - COMBANC S.A.'),
  array('id' => '56','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '281','codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE SERVICIOS TRANSACCIONALES CAJAVECINA S.A.'),
  array('id' => '57','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '279','codigoRegistro' => NULL,'nombre' => 'ADMINISTRADOR FINANCIERO TRANSANTIAGO S.A. - AFT'),
  array('id' => '58','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '284','codigoRegistro' => NULL,'nombre' => 'CORPLEGAL S.A.'),
  array('id' => '59','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '287','codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE PROMOCION DE PRODUCTOS BANCARIOS S.A. - PROBANC S.A.'),
  array('id' => '60','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '288','codigoRegistro' => NULL,'nombre' => 'SMU CORP S.A.'),
  array('id' => '61','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '289','codigoRegistro' => NULL,'nombre' => 'CONSORCIO TARJETAS DE CRÉDITO S.A.'),
  array('id' => '62','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '291','codigoRegistro' => NULL,'nombre' => 'SERVICIOS DE INFRAESTRUCTURA DE MERCADO OTC S.A.'),
  array('id' => '63','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '292','codigoRegistro' => NULL,'nombre' => 'CAR S.A. - TARJETA RIPLEY'),
  array('id' => '64','tipo' => 'Sociedades de Apoyo al Giro Bancarias','codigoSBIF' => '294','codigoRegistro' => NULL,'nombre' => 'CAT ADMINISTRADORA DE TARJETAS S.A.'),
  array('id' => '65','tipo' => 'Sociedades de Apoyo al Giro de Cooperativas','codigoSBIF' => '286','codigoRegistro' => NULL,'nombre' => 'GESTION DE RECAUDACION Y COBRANZA S.A. - GRC S.A.'),
  array('id' => '66','tipo' => 'Sociedades de Apoyo al Giro de Cooperativas','codigoSBIF' => '285','codigoRegistro' => NULL,'nombre' => 'INVERSIONES E INMOBILIARIA INVERMAS S.A. - INVERMAS S.A.'),
  array('id' => '67','tipo' => 'Sociedad de Leasing Inmobiliario','codigoSBIF' => '330','codigoRegistro' => NULL,'nombre' => 'BBVA SOC. DE LEASING INMOBILIARIO S.A.'),
  array('id' => '68','tipo' => 'Sociedad de Leasing Inmobiliario','codigoSBIF' => '331','codigoRegistro' => NULL,'nombre' => 'BANDESARROLLO SOC. DE LEASING INMOBILIARIO S.A'),
  array('id' => '69','tipo' => 'Sociedades de Cobranza','codigoSBIF' => '754','codigoRegistro' => NULL,'nombre' => 'SERVICIO DE NORMALIZACION Y COBRANZA NORMALIZA S.A.'),
  array('id' => '70','tipo' => 'Sociedades de Cobranza','codigoSBIF' => '755','codigoRegistro' => NULL,'nombre' => 'CENTRO DE RECUPERACION Y COBRANZA LTDA.'),
  array('id' => '71','tipo' => 'Sociedades de Cobranza','codigoSBIF' => '752','codigoRegistro' => NULL,'nombre' => 'BANCOESTADO SERVICIOS DE COBRANZA S.A.'),
  array('id' => '72','tipo' => 'Sociedades de Cobranza','codigoSBIF' => '753','codigoRegistro' => NULL,'nombre' => 'SOCOFIN S.A.'),
  array('id' => '73','tipo' => 'Sociedades de Cobranza','codigoSBIF' => '756','codigoRegistro' => NULL,'nombre' => 'RECAUDACIONES Y COBRANZAS S.A.'),
  array('id' => '74','tipo' => 'Sociedades de Factoring','codigoSBIF' => '363','codigoRegistro' => NULL,'nombre' => 'BCI FACTORING S.A.'),
  array('id' => '75','tipo' => 'Sociedades de Factoring','codigoSBIF' => '366','codigoRegistro' => NULL,'nombre' => 'BBVA FACTORING LTDA.'),
  array('id' => '76','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'ADMINISTRADORA PLAZA S.A.'),
  array('id' => '77','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'CRÉDITOS ORGANIZACIÓN Y FINANZAS S.A. - Cofisa S.A.'),
  array('id' => '78','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'FISO S.A.'),
  array('id' => '79','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'INVERSIONES Y TARJETAS S.A.'),
  array('id' => '80','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'INVERSIONES LP S.A.'),
  array('id' => '81','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'ISWITCH S.A.'),
  array('id' => '82','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'NEXUS S.A.'),
  array('id' => '83','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'OPERADORA DE TARJETAS LÍDER SERVICIOS FINANCIEROS S.A.'),
  array('id' => '84','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'PROMOTORA CMR FALABELLA S.A.'),
  array('id' => '85','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SERVICIOS Y ADMINISTRACIÓN DE CRÉDITOS COMERCIALES LÍDER S.A.'),
  array('id' => '86','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE CRÉDITOS COMERCIALES S.A .'),
  array('id' => '87','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD EMISORA DE TARJETAS C Y D S.A.'),
  array('id' => '88','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOLVENTA TARJETAS S.A.'),
  array('id' => '89','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'TECNOCOM PROCESADORA DE CHILE S.A'),
  array('id' => '90','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'TRANSBANK S.A.'),
  array('id' => '91','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'TRICARD S.A.'),
  array('id' => '92','tipo' => 'Emisores y Operadores de Tarjetas de Crédito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'OPERADORA DE PROCESOS S.A.'),
  array('id' => '93','tipo' => 'Operadores de Tarjetas de Pago con Provisión de Fondos','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'TECNOCOM PROCESADORA DE CHILE S.A'),
  array('id' => '94','tipo' => 'Operadores de Tarjetas de Pago con Provisión de Fondos','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'NEXUS S.A.'),
  array('id' => '95','tipo' => 'Sociedades Evaluadoras','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'CLASIFICADORA DE RIESGO HUMPHREYS LTDA.'),
  array('id' => '96','tipo' => 'Sociedades Evaluadoras','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'FELLER-RATE, CLASIFICADORA DE RIESGO LTDA.'),
  array('id' => '97','tipo' => 'Sociedades Evaluadoras','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'FITCH CHILE CLASIFICADORA DE RIESGO LTDA.'),
  array('id' => '98','tipo' => 'Sociedades Evaluadoras','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'INTERNATIONAL CREDIT RATING COMPAÑIA CLASIFICADORA DE RIESGO LTDA.'),
  array('id' => '99','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE GARANTÍA RECÍPROCA AVAL CHILE S.A.G.R'),
  array('id' => '100','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE GARANTÍA RECÍPROCA PROAVAL CHILE SOCIEDAD ANÓNIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '101','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE GARANTÍA RECÍPROCA CONFIANZA S.A.G.R'),
  array('id' => '102','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'COOPERATIVA DE GARANTÍA RECÍPROCA  CONGARANTÍA CGR'),
  array('id' => '103','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE GARANTÍA RECÍPROCA MASAVAL S.A.G.R'),
  array('id' => '104','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE GARANTÍA RECÍPROCA FIRST AVAL S.A.G.R.'),
  array('id' => '105','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'FIANZAS INSUR  SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '106','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SUAVAL SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '107','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'AGROAVAL SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '108','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'AVAL PYME SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '109','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'PYMER SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '110','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'CONTÉMPORA SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '111','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'MULTIAVAL SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '112','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOUTH CONE SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '113','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'AVALES Y GARANTÍAS PYMES SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '114','tipo' => 'Sociedades de Garantía Recíproca y Fogape','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOLUCIÓN AVAL SOCIEDAD ANONIMA DE GARANTÍA RECÍPROCA'),
  array('id' => '115','tipo' => 'Firmas Evaluadoras de Instituciones de Garantía Recíproca','codigoSBIF' => NULL,'codigoRegistro' => '01','nombre' => 'CLASIFICADORA DE RIESGO HUMPHREYS LTDA. '),
  array('id' => '116','tipo' => 'Firmas Evaluadoras de Instituciones de Garantía Recíproca','codigoSBIF' => NULL,'codigoRegistro' => '03','nombre' => 'ICR COMPAÑÍA CLASIFICADORA DE RIESGO LTDA.'),
  array('id' => '117','tipo' => 'Firmas Evaluadoras de Instituciones de Garantía Recíproca','codigoSBIF' => NULL,'codigoRegistro' => '04','nombre' => 'FELLER-RATE COMPAÑÍA CLASIFICADORA DE RIESGO LIMITADA'),
  array('id' => '118','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '001','nombre' => 'PRICEWATERHOUSECOOPERS CONSULTORES, AUDITORES Y COMPAÑIA LTDA.'),
  array('id' => '119','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '002','nombre' => 'KPMG AUDITORES CONSULTORES LTDA.'),
  array('id' => '120','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '003','nombre' => 'ERNST &YOUNG SERVICIOS PROFESIONALES DE AUDITORIA Y ASESORIAS LTDA.'),
  array('id' => '121','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '004','nombre' => 'BDO AUDITORES & CONSULTORES LIMITADA'),
  array('id' => '122','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '005','nombre' => 'DELOITTE AUDITORES Y CONSULTORES LTDA.'),
  array('id' => '123','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '006','nombre' => 'SURLATINA AUDITORES LTDA.'),
  array('id' => '124','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '007','nombre' => 'VALENZUELA Y ASOCIADOS LIMITADA'),
  array('id' => '125','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '009','nombre' => 'PKF CHILE AUDITORES CONSULTORES LTDA.'),
  array('id' => '126','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '010','nombre' => 'HORWATH HB AUDITORES CONSULTORES LIMITADA'),
  array('id' => '127','tipo' => 'Auditores Externos','codigoSBIF' => NULL,'codigoRegistro' => '011','nombre' => 'CONSAUDIT INTERNATIONAL AUDITORÍA & CONTROL LTDA.'),
  array('id' => '128','tipo' => 'Almacenes Generales de Depósito registrados en SBIF','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'ALMACENES DE DEPÓSITOS NACIONALES S.A. "ALMADENA"'),
  array('id' => '129','tipo' => 'Almacenes Generales de Depósito registrados en SBIF','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'ALMACENES GENERALES DE DEPÓSITO STORAGE S.A.'),
  array('id' => '130','tipo' => 'Almacenes Generales de Depósito registrados en SBIF','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'ALMACENES GENERALES DE DEPÓSITO TRANSWARRANTS S.A.'),
  array('id' => '131','tipo' => 'Firmas Evaluadoras de Almacenes Generales de Depósito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'PRICEWATERHOUSECOOPERS, CONSULTORES, AUDITORES Y CÍA. LTDA.'),
  array('id' => '132','tipo' => 'Firmas Evaluadoras de Almacenes Generales de Depósito','codigoSBIF' => NULL,'codigoRegistro' => NULL,'nombre' => 'SOCIEDAD DE SERVICIOS GENERALES LTDA. "SEGRAL"')
);
